import { Menu } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "./NavBar";
import Search from "./Search";
import MenuPage from "./MenuPage";
import Footer from "./Footer";
// import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chakra UI layout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        />
      </Head>

      <main>
        <NavBar />
        <Search />
        <MenuPage />
      </main>
      <br />

      <Footer />
    </div>
  );
};

export default Home;
